name: Report a bug.
description: Found a bug with the library? We'll fix it!
title: "bug: "
labels: ["bug"]
assignees:
  - i0bs
body:
  - type: textarea
    id: traceback
    attributes:
      label: What's the error?
      description: Please provide a copy of your console/terminal with the error.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our library are you using?
    validations:
      required: true
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By checking, you accept that you will follow our contribution standards.
    validations:
      required: true
